### ISSUE TITLE
how to override the default error code of 400 to a more specific 422?

### ISSUE THREAD

**Issue by johndcarmichael** [arb/celebrate#113]
- `node` version - 10 lts
- `celebrate` version - 10.0.0
- `joi` version (via `npm ls --depth=0 | grep joi`) - not important

I am writing a collection of micro services that will work in combination with a few others, not all written in node. I need to align the error status code with the rest of the services, to http status code 422. This package is nice and simple but how can i acheive this, cannot see anything in the readme on changing it from 400.

**Comment by johndcarmichael** [comment]
As some what of a dirty hack, but dictating the status code feels like it should be done in the "errors" middleware:
```js
export default () => {
  return (err, req, res, next) => {
    if (err.joi) {
      res.status(422).json(err)
    } else {
      next(err)
    }
  }
}
```

**Comment by arb** [comment]
@johndcarmichael please check https://github.com/arb/celebrate#errors about `celebrate` errors. Basically, write your own `celebrate` error handler and check `isCelebrate(err)` to determine if the error came from a `celebrate` validation failure.
