### ISSUE TITLE
Upgrade Joi@16.0.0

### ISSUE THREAD

**Issue by arb** [arb/celebrate#116]
https://github.com/hapijs/joi/issues/1941 (Root.validate is gone)

https://github.com/hapijs/joi/issues/2037 (Full change log)

**Comment by rdonelson** [comment]
I'm hoping to use this for a work project and was wondering if there's an estimated release date for 11.0.0? Thanks!

**Comment by arb** [comment]
It's looking like I'll have a release candidate in the next week or so. #136 is the last big PR that needs to land.
