### ISSUE TITLE
Validate req.params

### ISSUE THREAD

**Issue by sjgmojica** [arb/celebrate#127]
Hi Just wanna ask how can I validate the value of req.params from middleware? Thanks

**Comment by arb** [comment]
Check out https://github.com/arb/celebrate/blob/master/test/integration.test.js#L53-L74 for an in-code example.

Generally speaking, you'd do
```
celebrate({
  params: { //schema goes here }
})
```

**Comment by sjgmojica** [comment]
Nice.Thanks
