### ISSUE TITLE
Question: how to extend Joi with a validator that needs to read request's headers

### ISSUE THREAD

**Issue by ctessier** [arb/celebrate#128]
Hi,

I need to extend Joi with a custom type validator that would validate a JSON body property. Although, in order to be able to validate this value, I need a custom request header that is also being sent in the request.

I seem to not be able to access the request object in the rule of my validator. Can you think of any other possibility to do that? Maybe a way to define a peer dependency between a JSON body property and a header?

Thank you very much for your help.
Regards

**Comment by ctessier** [comment]
Seems like `reqContext` could do the trick for me. Will try it out..
If you have an example so long, I'll take it :)

Thanks

**Comment by MuhamadOmr** [comment]
@arb still is it possible to inject an extended joi , can you elaborate more on that if it is possible ?

**Comment by ctessier** [comment]
Thanks @arb, `reqContext` did the trick. I could then simply use `options.context.headers.MY_HEADER` in the `rules`'s `validate` method of my Joi extension 👍 
The exemple with the query param is very interesting too!
