### ISSUE TITLE
Validate array in query parameters?

### ISSUE THREAD

**Issue by vedantroy** [arb/celebrate#154]
If we have an array in the query parameters, how do we validate it?

**Comment by arb** [comment]
Assuming the items in your query string are objects... you would use something like

```js
[Segments.QUERY]: Joi.array().items(Joi.object(.....))
```

Check [here](https://github.com/hapijs/joi/blob/master/API.md#arrayhasschema) for a more complete example. Per the README [here](https://github.com/arb/celebrate#issues), I'm not able to give help writing Joi validation schemas, but there are plenty of other resources to help you do so. 

- Read the Joi documentation
- ask for help in the hapijs slack
- ask on StackOverflow

Any of those options would give you a much more specific help on writing Joi schemas. If you have any additional questions about celebrate specifically, please feel free to open a new issue.

**Comment by vedantroy** [comment]
I tried using `Joi.array()`, but it only recognized the array as a string. `Joi.number`, `Joi.string`, and `Joi.boolean` all work fine.

**Comment by arb** [comment]
Then the way you're parsing the query string doesn't result in an array. Make sure `req.query` is the array you think it should be before worrying about validating it.

**Comment by vedantroy** [comment]
Thanks for the help so far. To clarify, an array is one of the query parameters in the query string. Also, every parameter in the query string/`Segments.QUERY` is, by default, a string, the only reason `Joi.number`  and `Joi.boolean` work is because they accept strings. Is there some sort of middleware I have to plug in to parse the values in the query string into actual JS values?

`?parameter1=[value1,value2]&parameter2=someBoolean&parameter3=someNumber`

**Comment by arb** [comment]
https://expressjs.com/en/resources/middleware/body-parser.html
