### ISSUE TITLE
Bump version of @hapi/joi to 16.1.8

### ISSUE THREAD

**Issue by andrewoh531** [arb/celebrate#159]
I noticed a change was made to `@hapi/joi` in version 16.1.8 which I want to utilize.

Would you be able to bump the version used internally in `package-lock.json`?

**Comment by andrewoh531** [comment]
> I'd like to not have to publish a new version of celebrate every time joi is update. I specifically used joi `16.x.x` in `package.json` to prevent this problem 🤔

I think if you want to achieve that you should be listing `joi` as a peer dependency rather than a direct dependency. 

This [article](https://medium.com/angular-in-depth/npm-peer-dependencies-f843f3ac4e7f) explains quite well when you should use a `peerDependency` vs a regular `dependency`. Since `joi` isn't being used internally and IS being exposed by `celebrate` I think it makes sense for it to be a `peerDependency`.

There are ways to override versions using `resolutions` in `yarn` but I don't believe there is an equivalent for `npm`, which unfortunately is what we're using.

**Comment by arb** [comment]
Have you tried removing your node_modules folder and re-installing your dependencies? `package-lock.json` isn't included in the tar when you install things from `npm` so I'd be surprised if it was having any effect here.

**Comment by andrewoh531** [comment]
You're right that seems to be the case. I probably wasn't looking closely enough thanks!

And was going to ask you about @hapi/joi version 17 but looks like you're already on it! https://github.com/arb/celebrate/issues/162
