### ISSUE TITLE
Joi Version Bump

### ISSUE THREAD

**Issue by arb** [arb/celebrate#162]
Bump to version 17.

https://github.com/hapijs/joi/issues/2262

**Comment by Kamahl19** [comment]
Joi 17 only supports Node 12+ but Celebrate seems to require Node 10+. Will Joi work on node 10 as well?

**Comment by arb** [comment]
`joi` got rid of the `engine` value in it's package.json, so it's hard to know. You could try it and see what happens, in all likelihood though, I'll update celebrates engine value to match what joi is testing for (which is probably 12 and the next major)

**Comment by Kamahl19** [comment]
Just trying it out is not enough, it could break in just some usecase of Joi. Wouldnt it be better to stay on  older Joi, the one that supports node 10? This crazy move Hapi did to cut node 10 a year before it goes out of LTS it not good.

**Comment by arb** [comment]
One of the project goals of celebrate is to keep joi updated with latest. I agree with you though on principle, I don't like the speed that "old" versions of Node are deprecated in the hapi ecosystem, but there really isn't anything I can do about it.

If you want to use an older version of Joi, roll back to version 11 of celebrate. That used a version that was supported in Node 10.
