### ISSUE TITLE
Option for Celebrate to not short-circuit request validation

### ISSUE THREAD

**Issue by chuck-huey** [arb/celebrate#178]
I'm wondering if you could add an option for `celebrate` to get all possible errors before moving to the error handler. The current implementation renders the `abortEarly` option from `Joi` redundant

**Comment by arb** [comment]
Are you asking for an option so that if there are validation errors in headers, body, and query that you want all of them reported together rather than failing fast on headers?

**Comment by chuck-huey** [comment]
Yes, please. I would like that very much

**Comment by superh2m** [comment]
+1 for this feature :pray:

**Comment by TarineM** [comment]
+1

**Comment by cabardos** [comment]
+1

**Comment by Arthurhall** [comment]
+1

**Comment by arb** [comment]
I've been thinking about this and it's a pretty big change. It would change the shape of the error object so that's breaking. Would the response be a object where the `key` is the failed segment and the `value` would be a `CelebrateError`.

**Comment by arb** [comment]
I've started working on this in #185. For those of you interested in this feature, check out my draft PR and leave any questions or concerns.

**Comment by arb** [comment]
Any here interesting in reviewing #185? I think it's ready to go.
