### ISSUE TITLE
how to access validateAsync

### ISSUE THREAD

**Issue by johndcarmichael** [arb/celebrate#191]
- `node` version - 12 lts latest patch
- `celebrate` version - 13.0.0

https://joi.dev/api/?v=17.2.1#anyvalidateasyncvalue-options

How can i access the validateAsync api of Joi from celebrate?

**Comment by arb** [comment]
https://github.com/arb/celebrate/blob/master/lib/celebrate.js#L29-L30 it already uses `validateAsync`.
