### ISSUE TITLE
isCelebrateError method not exported :3 

### ISSUE THREAD

**Issue by hoangnguyennn** [arb/celebrate#193]
- `node` version - v12.18.3
- `celebrate` version - 13.0.0 - newest

I try to use `isCelebrateError` method and I get an error like this:

![Error](https://user-images.githubusercontent.com/40981446/92306572-53f8ef00-efba-11ea-959d-86a956286a62.png)

**Comment by arb** [comment]
The code functions. This is an issue with the TS file. Pull requests welcome 😄
