### ISSUE TITLE
Feature request: more errors options

### ISSUE THREAD

**Issue by dn-l** [arb/celebrate#196]
Hi there!
Would be really neat to have more `errors` middleware options to give some flexibility:
1. message `string|false| undefined|null|`
Currently it is "celebrate request validation failed" which I'd like to omit
2. Error `string|false|undefined|null`
Same purpose. For example, `error: 'Bad Request: validation failed'`
3. mapped `boolean`
Will do map to field names. This is the current response:
<img width="683" alt="Screen Shot 2020-09-13 at 11 32 58" src="https://user-images.githubusercontent.com/7160998/93013884-e6018880-f5b4-11ea-8638-6b469d1772c7.png">
Which is not really usable on the UI side.
With mapped it would look like this:
<img width="683" alt="Screen Shot 2020-09-13 at 11 31 13" src="https://user-images.githubusercontent.com/7160998/93013839-a9359180-f5b4-11ea-9936-a0ef9745725d.png">

Here's the code (not sure if `path.join('.')` is the best solution tho):
```js
function formatCelebrateErrors (err) {
  const result = {}
  for (const [key, { details }] of err.details) {
    result[key] = details.reduce((acc, { path, message }) => {
      acc[path.join('.')] = {
        message
      }
      return acc
    }, {})
  }
  return result
}
```

4. Validation details field name -- to change `validation` to something different, for example `details`

Tell me what do you think?

**Comment by arb** [comment]
This would be a very large amount of customization to expose to the `errors` API. Have you looked into writing your own errors middleware for handling celebrate errors and checking the incoming error with `isCelebrateError`?

**Comment by dn-l** [comment]
Gotya. Yea that's exactly what I did in my case.
