### ISSUE TITLE
Celebrate 13.x + Joi custom error --> throws AssertionError

### ISSUE THREAD

**Issue by palazzetti** [arb/celebrate#197]
- `node` version - 14.5.0
- `celebrate` version - 13.0.2
- `joi` version (via `npm ls --depth=0 | grep joi`) -17.2.1

My `joi` schema looks like this:

![image](https://user-images.githubusercontent.com/49283657/93456444-fe87e080-f8dd-11ea-8368-389c777b033b.png)
![image](https://user-images.githubusercontent.com/49283657/93456806-79e99200-f8de-11ea-90c1-317cc421ab14.png)

Here is an example value that is not working as expected:

![image](https://user-images.githubusercontent.com/49283657/93457026-c9c85900-f8de-11ea-9d66-4b561e20ddfb.png)

The issue I am having with `celebrate` is:

After the update to celebrate 13.x, when is time to throw the error from joi i get the above error.
From what I understand, the error generated by Joi doesn't like to celebrate. I've already tried using CelebrateError without success.
Thanks.

**Comment by arb** [comment]
You'd want to throw a Joi Validation [error](https://joi.dev/api/?v=17.2.1#validationerror) in your first screenshot, not a built in `Error` object. Also, if you're just trying to control the message, check out the [`.message()`](https://joi.dev/api/?v=17.2.1#anymessagemessage) API.

**Comment by monsterooo** [comment]
> You'd want to throw a Joi Validation [error](https://joi.dev/api/?v=17.2.1#validationerror) in your first screenshot, not a built in `Error` object. Also, if you're just trying to control the message, check out the [`.message()`](https://joi.dev/api/?v=17.2.1#anymessagemessage) API.

```javascript
route.post("/register", celebrate({
    [Segments.BODY]: Joi.object({
      name: Joi.string().$.min(3).max(24).message('error message info'),
    })
  }), async (req, res) => {
    res.json({});
  });
```
😁
