### ISSUE TITLE
integrate celebrate with multipart/form-data

### ISSUE THREAD

**Issue by LucasRobs** [arb/celebrate#204]
- `node` version - v12.16.3
- `celebrate` version - ^13.0.4
- `joi` version (via `npm ls --depth=0 | grep joi`) - 17.3.0

My `joi` schema looks like this: 

```js
routes.post('/product', celebrate({
    [Segments.HEADERS]: Joi.object({
        authorization: Joi.number().required()
    }).unknown(),
    [Segments.BODY]: Joi.object().keys({
        nameProduct: Joi.string().required(),
        codeProduct: Joi.string().required(),
        priceProduct: Joi.number().required(),
        descriptionProduct: Joi.string().optional(),
        weightProduct: Joi.string().required(),
        fkIdType: Joi.number().required(),
        image: Joi.string().optional(),
    })
}), upload.single('image'), ProductController.create);
```

Here is an example value that is not working as expected:

```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "celebrate request validation failed",
  "validation": {
    "body": {
      "source": "body",
      "keys": [
        "codeProduct"
      ],
      "message": "\"codeProduct\" is required"
    }
  }
}
```

The issue I am having with `celebrate` is:

Hello, I'm fighting with a great problem, I can`t to integrate celebrate with multipart/form-data, can you help me?

**Comment by joaovictor3g** [comment]
so much important issue to us!

**Comment by arb** [comment]
Can I see more of your express server code? Also what module are you trying to use to handle multipart/form-data? Your GitHub issue is pretty bare. There are probably fifteen different modules out there for multipart form data and they all work different 😅

**Comment by LucasRobs** [comment]
what part of my express server code do you want experimentally?I am using Multer. could you leave a link with one of those solutions that you talked about?
thank you for all attention :+1:

**Comment by arb** [comment]
Try moving the `celebrate` call after the call to `upload.single`. My hunch is that multer is parsing the incoming payload for you so if you try to validate it with celebrate before it's been parsed, `req.body` will likely be empty.

Should look something like:

```js
routes.post('/product', upload.single('image'), celebrate(/*..same as above*/), ProductController.create);
```

**Comment by LucasRobs** [comment]
it worked dear friend, thank you very much for your help :construction_worker:

**Comment by saymondamasio** [comment]
but particularly I would like to validate first before uploading so the images would not be burned to disk for no reason
