### ISSUE TITLE
any.external async support

### ISSUE THREAD

**Issue by basaran** [arb/celebrate#205]
Hello,

Does celebrate support async validation from joi any.external?

https://joi.dev/api/?v=17.3.0#anyexternalmethod-description

Thank you,

**Comment by arb** [comment]
It supports `extend` per the tests [here](https://github.com/arb/celebrate/blob/master/test/celebrate.test.js#L235-L268). I would suspect `any.external` would also work. Also, all validations happen async now when I updated to a newer version of Joi.

**Comment by basaran** [comment]
Thank you, I will test it over the weekend and update it here. I ran into an issue with another library where  the error thrown within the any.external was not caught accordingly so I figured I should ask first. Much appreciated.
