### ISSUE TITLE
Celebrate  V13 not able to validate params data which is in array.

### ISSUE THREAD

**Issue by airrakeshkumarsharma** [arb/celebrate#207]
- `node` version - 14.15.4
- `celebrate` version - 13.0.4

My `joi` schema looks like this:
```

Joi.object().keys({
  // Filters
  filters: Joi.array()
    .items({
      key: Joi.string().required(),
      type: Joi.string(),
      value: [Joi.string().trim(), Joi.array(), Joi.boolean()],
      upperValue: [Joi.number(), Joi.string().isoDate().allow(null)],
      lowerValue: [Joi.number(), Joi.string().isoDate().allow(null)],
      operation: Joi.string()
    })
    .default([]),

  // Sort
  sort: Joi.array()
    .items({
      key: Joi.string().required(),
      order: Joi.number().required()
    })
    .default([]),

  // Pagination
  perPage: Joi.number().min(1).default(CONSTANTS.PAGINATION.PER_PAGE),
  pageNumber: Joi.number().min(1).default(1)
});

```

Here is an example value that is not working as expected:

`?filters=[{"key":"userType","value":"STUDENT"}, {"type":"hash","key":"email","value":"abhishek.k.vghgghj@gmail.com"}]`

The issue I am having with `celebrate` is:

*When I go to version 10 then celebrate is working fine and it is able to validate the params but when I just shift to v13 then it is not able to validate*

**Comment by arb** [comment]
What else changes? Are you using the bundled version of Joi that celebrate exports or are you using one from `package.json`? 

What do you mean "not able to validate"? In what way?

Finally, you'll get better and faster responses if your issues are formatted correctly.

**Comment by airrakeshkumarsharma** [comment]
Yes, I am using the bundled version which comes with celebrate. 
And thanks for your comments.

**Comment by arb** [comment]
Are you still having a problem or can this issue be closed?

**Comment by Marsup** [comment]
This is very likely due to your joi upgrade, it was described as a breaking change in joi@16, see https://github.com/sideway/joi/issues/2037 section `Array and object string coercion`.

**Comment by arb** [comment]
Have you tried setting `convert: true` in the joi options? Also, you still haven't explained precisely HOW it is not able to validate. What error are you getting? What data are you passing? What does `req.query` look like before you try to validate it. I can't really help because your responses do not include enough information.

**Comment by airrakeshkumarsharma** [comment]
Yes, I set the `{ convert: true }` but this also does not work.

Here is my input
`filters=[{"key":"userType","value":"STUDENT"}, {"type":"hash","key":"email","value":"abhishek.k.v83408@gmail.com"}]`

Output
`
  details: Map(1) {
    'query' => [Error [ValidationError]: "filters" must be an array] {
      _original: [Object],
      details: [Array]
    }
  },
  [Symbol(celebrated)]: true
}
`

**Comment by arb** [comment]
Log out `req.query` in some middleware before calling `celebrate`.

**Comment by Marsup** [comment]
I already explained the problem, you just have to find a way to apply the solution with celebrate. Looks like there's [a test](https://github.com/arb/celebrate/blob/master/test/celebrate.test.js#L235) that demonstrates how to extend, it's just not documented.
