### ISSUE TITLE
Typescript inference from arguments

### ISSUE THREAD

**Issue by alburkerk** [arb/celebrate#212]
- `node` version - 10.15
- `celebrate` version - 13.0.4
- `joi` version (via `npm ls --depth=0 | grep joi`) - 17.3.0
- `@types/joi` version (via `npm ls --depth=0 | grep joi`) - 17.2.3

I am concerned with the celebrate function typing. Any reason why you would not want to infer typing from arguments ? I see several benefits:

- Less code 
- Stronger code. Currently, you can check in runtime for a schema and put a totally different type in celebrate generic arguments. 

It would be better if celebrate inferred req.body type directly from the body argument. Same for query or params.

I had it working with the following fix: 

```typescript
export interface SchemaOptions<P=ParamsDictionary, ReqBody=any, ReqQuery=Query> {
    /**
     * When `params` is set, `joi` will validate `req.params` with the supplied schema.
     */
    params?: Joi.Schema<P>;
    /**
     * When `headers` is set, `joi` will validate `req.headers` with the supplied schema.
     */
    headers?: object;
    /**
     * When `query` is set, `joi` will validate `req.query` with the supplied schema.
     */
    query?: Joi.Schema<ReqQuery>;
    /**
     * When `cookies` is set, `joi` will validate `req.cookies` with the supplied schema.
     */
    cookies?: object;
    /**
     * When `signedCookies` is set, `joi` will validate `req.signedCookies` with the supplied schema.
     */
    signedCookies?: object;
    /**
     * When `body` is set, `joi` will validate `req.body` with the supplied schema.
     */
    body?: Joi.Schema<ReqBody>;
}

/**
* Creates a celebrate middleware function.
*/
export declare function celebrate<P=ParamsDictionary, ResBody=any, ReqBody=any, ReqQuery=Query>(requestRules: SchemaOptions<P, ReqBody, ReqQuery>, joiOpts?: ValidationOptions, opts?: CelebrateOptions): RequestHandler<P, ResBody, ReqBody, ReqQuery>;
```

You can see in the attached picture that typing is inferred correctly based on body arguments provided. 

Only downside: I had to make a small change to Joi types, to make Joi.Schema generic for ObjectSchema. But it should be very easy to make this change accepted because it's a seamless change:

```typescript 

// From this
    type Schema =
        | AnySchema
        | ArraySchema
        | AlternativesSchema
        | BinarySchema
        | BooleanSchema
        | DateSchema
        | FunctionSchema
        | NumberSchema
        | ObjectSchema
        | StringSchema
        | LinkSchema
        | SymbolSchema;

// to this
    type Schema<P = any> =
        | AnySchema
        | ArraySchema
        | AlternativesSchema
        | BinarySchema
        | BooleanSchema
        | DateSchema
        | FunctionSchema
        | NumberSchema
        | ObjectSchema<P>
        | StringSchema
        | LinkSchema
        | SymbolSchema;
```
![image](https://user-images.githubusercontent.com/43244164/106266735-17f44e00-6229-11eb-960e-29fdbcf76f55.png)

Are you interested in a PR with those changes ?

**Comment by alburkerk** [comment]
I created the [PR](https://github.com/sideway/joi/pull/2551) in joi repo

**Comment by alburkerk** [comment]
Why would you close ? Joi juste merged my PR, I will create a celebrate PR for this issue.

**Comment by arb** [comment]
I closed this because I thought the only change needed to happen was in Joi, which landed.

**Comment by outranker** [comment]
Can we reopen this issue?
I am going to create a PR for this. I think this will be very useful feature
