### ISSUE TITLE
Curried celebrator does not work as described in docs

### ISSUE THREAD

**Issue by jasmine-q** [arb/celebrate#215]
- `node` version - v10.14.1
- `celebrate` version - 13.0.4
- `joi` version (via `npm ls --depth=0 | grep joi`) - 17.3.0

Here is an example value that is not working as expected:

Running `celebrator({ reqContext: true, mode: Modes.FULL }, { convert: false })(schema)` results in:
```
ValidationError: {
  "convert" [1]: false
}

[1] "convert" is not allowed
```

Running `celebrator({ reqContext: true, mode: Modes.FULL }, { convert: false }, schema)` results in:
```
ValidationError: {
  "mode": "full",
  "reqContext" [1]: true
}

[1] "reqContext" is not allowed
```

However, `celebrator({ reqContext: true, mode: Modes.FULL })({ convert: false })(schema)` works!

The issue I am having with `celebrate` is:

`celebrator` isn't able to be used in all the ways listed in the docs:
```js
let c = celebrator(opts)(joiOpts)(schema); // working
c = celebrator(opts, joiOpts)(schema); // does not work
c = celebrator(opts)(joiOpts, schema); // does not work
c = celebrator(opts, joiOpts, schema); // does not work
```

**Comment by arb** [comment]
It sure is!! Thanks for reporting. I've got a simple fix locally. I think I will make this a breaking change in case people were using it in the broken state before. What are your thoughts?

**Comment by jasmine-q** [comment]
> Hey @jasmine-q, can you give #216 a spin when you get a minute? Does that solve your issue?

Hi @arb, sorry I didn't get back to you earlier. Yes that's working great for me and solves my issue, thanks for the quick reply and fix!

Making this a breaking change makes sense to me 👍
