### ISSUE TITLE
Set default value if validation is failed. especially for query params which are optional

### ISSUE THREAD

**Issue by pnutmath** [arb/celebrate#226]
- `node` version - v12.22.1
- `celebrate` version - 15.0.0
- `joi` version (via `npm ls --depth=0 | grep joi`) - NA

The issue I am having with `celebrate` is:

Set default value if validation is failed. especially for query params which are optional. Can we support this?

**Comment by arb** [comment]
Joi has a `.default()` method available on every type. See [this test](https://github.com/arb/celebrate/blob/master/test/celebrate.test.js#L130-L171) for a code example.

**Comment by pnutmath** [comment]
Consider below scenario:

```
 page: Joi.object().keys({
    page: Joi.number().min(1).default(1),
    limit: Joi.number().min(1).default(10),
  }),
```

here, in case my request is like `/?page=&limit=0`  

then page failed because it considered as string and limit failed because of min criteria.

As query params are optional, I am interested to set default value even after validation fails, without rejecting request. I don't think its happening right now

**Comment by arb** [comment]
It's rejecting because the schema says that `limit` minimum is 1, but it's being sent to 0 so the request is invalid. `celebrate` doesn't apply the transformations unless the request passes validation. 

If you make `limit` 2, then it should pass and `page` should default to 1.

**Comment by pnutmath** [comment]
Yes understood @arb, but I am saying like even though it fails validation for query params and if we have set default then validation should pass with default value. 

I am suggesting this for query params only.

**Comment by AdamAld** [comment]
@pnutmath Your suggestion breaks standard validation for optional keys in the schema.. A possible workaround could be to use the `.when(..)` functionality on the schema itself to mutate the validation of that field ([`any().when(..)` Docs](https://joi.dev/api/?v=17.4.2#anywhencondition-options)), or using any of their Alternative helpers [(`alternatives.conditional|match|try(..)` Docs)](https://joi.dev/api/?v=17.4.2#alternatives).

Hope this helps!
