### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by anukul** [arb/celebrate#227]
Any ideas or plans for integration with Swagger / OpenAPI?

**Comment by arb** [comment]
We looked into a swagger integration previously but we didn't get very far. The compiled Joi schema is technically attached to the [result function](https://github.com/arb/celebrate/blob/master/lib/celebrate.js#L175) of `celebrate()`.

```js
const x = celebrate(...);
console.log(x._schema)
```

So you could start trying to map Joi schema's to whatever shape Swagger wants. That's what we tried a few years ago.
