### ISSUE TITLE
 Mode FULL doesn't seem to be working.

### ISSUE THREAD

**Issue by JdSeus** [arb/celebrate#231]
- `node` version - v14.17.0
- `celebrate` version - 15.0.0
- `joi` version - 17.4.2

Hello everyone, I'm trying to use Celebrate on mode FULL but it doesn't seem to be working. 

Here is my Schema:

![image](https://user-images.githubusercontent.com/65918284/142771634-78ec5891-77df-43cc-b062-90cb8d4667ad.png)

(I have tried before this way, but got the same results 
![image](https://user-images.githubusercontent.com/65918284/142772328-0940c281-6ee3-488c-afe8-a45f194a470f.png)
)

This is my my require at ClientsController (where exports.postClientValidation is):
![image](https://user-images.githubusercontent.com/65918284/142771498-ac7641bd-5b6f-43fc-84d5-9f477ac82293.png)

This is how i'm using Celebrate:

![image](https://user-images.githubusercontent.com/65918284/142771377-4c59995d-350f-4898-9ee5-76026c88abdc.png)

ClientsController.postClient is irrelevant in this case, since i'm testing the validation of Celebrate, which is encapsulated in ClientsController.postClientValidation.

This is the result on Postman, when 3 fields are deselected:

![image](https://user-images.githubusercontent.com/65918284/142772491-0ba07cd9-b95c-445d-9742-6d3412696100.png)

If I understood it correctly, it should be something like that on mode full: 

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Validation failed",
    "validation": {
        "body": {
            "source": "body",
            "keys": [
                "nome", 
                "endereco", 
                "cep"
            ],
            "message": "\"nome\" is required. \"endereco\" is required. \"cep\" is required."
        }
    }
}
```
I'm not sure about the validation message though.

Anyway, is it something I did wrong? Or mode full is not working?

Thanks in advance.

**Comment by JdSeus** [comment]
Sorry. It seems to be duplicated of https://github.com/arb/celebrate/issues/228.

I recommend put in the documentation that joiOptions should be something like that {warnings: true, abortEarly: false} to full mode work properly.

![image](https://user-images.githubusercontent.com/65918284/142772827-58be93dd-ff5c-44ba-8368-973d9f91c52b.png)


![image](https://user-images.githubusercontent.com/65918284/142772820-a598bd16-e446-452e-bb53-93e9f6bc44b9.png)

Anyway, thanks.

**Comment by arb** [comment]
Any PR that improves the documentation are always welcome 😄
