### ISSUE TITLE
Examples in TypeScript too

### ISSUE THREAD

**Issue by TomMiller-mas** [arb/celebrate#232]
This package looks awesome, but I am new to javascript and TypeScript and really need an example of the syntax for TypeScript. Please don't put the schema inside the route.  I want to use the same route for inserts and updates and need an example of the syntax of consuming a stand-alone schema (which I can't find anywhere).

A schema based on a user would be great: email, password, phone number, etc.  

A couple of post routes: Insert and Update 

I hope you will put something together.

**Comment by Sljcom** [comment]
I just came across this package and your comment, but I highly doubt Typescript will do any good here as Typescript is just for validating that the data you pass around your application has the correct form during DEVELOPMENT. 

All Typescript gets removed when you compile your application and it will not do any validation or checks once that happens. It is just for development purposes. Typescript also has no control over data that comes from other places.

**Comment by Jendorski** [comment]
Honestly, a typescript example is needed, thank you.
