### ISSUE TITLE
node 16 Object.defineProperty compatibility

### ISSUE THREAD

**Issue by slimee** [arb/celebrate#235]
Is using two times celebrate for the same route discouraged?

Maybe that will interest you:

Celebrate can't be used twice on the same endpoint when using node 16 instead of node 14.
It's because of `Object.defineProperty(request, 'headers', ...) that is made, the property is made read-only the first time, so it fails the second time.
Why not just do "request['headers'] = value" ?

We are currently changing our code to have only one celebrate call.

Regards

**Comment by arb** [comment]
I would suggest only using one celebrate call per route and put all of the validation rules into that single call. I'm actually not sure the use case where you would want to call it multiple times 🤔

`request['headers'] = value` fails on newer version of Express if you're interested in the full story, check out https://github.com/arb/celebrate/issues/42

I'm not a fan of that line you're referring to, but it was easier than trying to get express to change their code/APIs.
