### ISSUE TITLE
joi.alternatives error message too generic

### ISSUE THREAD

**Issue by maxuai** [arb/celebrate#241]
- `node` version - 18.12.1
- `celebrate` version - 15.0.1
- `joi` version (via `npm ls --depth=0 | grep joi`) - 17.2.3

My `joi` schema looks like this:

`{
      [Segments.QUERY]: {
        param: Joi.alternatives().try(Joi.object({
          name: Joi.string(),
        }), Joi.object({
          name: Joi.number(),
        })),
    }`

Here is an example value that is not working as expected:

`(param: { name: true })`

The issue I am having with `celebrate` is:

When using `joi.alternatives` with objects and none of the alternatives matches the error message is too generic like `"message": "\\"param\\" does not match any of the allowed types"`. What would be needed is to add the `context` from the the error details to the `validation` object in the error response.

**Comment by maxuai** [comment]
I would have a branch with a fix ready, but am am not allowed to push ;)

**Comment by arb** [comment]
Hi @maxuai if you're still interested in adding this, please folk this project and open a pull request; I'd be happy to review.
