### ISSUE TITLE
node v6 support (joi v12)

### ISSUE THREAD

**Issue by codyzu** [arb/celebrate#77]
- `node` version - 6.14.2
- `celebrate` version - 8.0.0

Is using the latest `v7.x.x` release the best way to work with node v6 (joi v12 is the last version that supports node v6)?

Why? I'm deploying to firebase / google cloud functions that run node v6 (limiting joi to v12). :crying_cat_face: 

Thanks for the great module!

**Comment by arb** [comment]
If you're on node 6, then you need `celebrate@7.x.x`. The joi dependency basically forced my hand regarding the allowable node version celebrate supports. The latest version of joi only works in node >= 8.9. There aren't any big changes between celebrate 7 and 8. Mostly just joi and node version changes.
