### ISSUE TITLE
How to validate multipart/form-data

### ISSUE THREAD

**Issue by whisher** [arb/celebrate#79]
Hi, there.
Sorry to bother you but
I've got problems to validate multipart/form-data
from an angular app

## Express
```javascript
exports.create = {
  body: {
    content: Joi.string().required(),
    title: Joi.string().required()
  }
};

router.post('',
  celebrate(validators.create),
  jwtVerify,
  extractFile,
  controllers.create
);
```

## Angular
```javascript
add(data): Observable<Post> {
    const { title, content, isDraft, image } = data;
    const postData = new FormData();
    postData.append('title', title);
    postData.append('content', content);
    postData.append('isDraft', isDraft);
    postData.append('image', image, title);
    return this.http.post<Post>(this.postsUrl, postData)
   .pipe(catchError((error: any) => HttpErrorHandler.handle(error)));
  }
```

The error message is
*{"isJoi":true,"name":"ValidationError","details":[{"message":"\"content\" is required","path":["content"],"type":"any.required","context":{"key":"content","label":"content"}}],"_object":{},"_meta":{"source":"body"}}*

Can you help me, please ?

**Comment by arb** [comment]
What multipart form middleware are you using for express? How does it expose multipart form data to your other functions? Also, it's sort of atypical to send data back to the server like this when you could just send JSON rather than the overhead of `FormData`.

**Comment by whisher** [comment]
Hi Arb,
thanks for the reply.
I know using FormData can be overload
but I'm working on a form with a image to upload
so the only way to accomplish the task is using FormData.
I'm using **multer** as multipart form middleware.

**Comment by arb** [comment]
Before `celebrate(validators.create)`, add another middleware and log out `req.body` to see what's in there before the validation occurs.

**Comment by whisher** [comment]
```javascript
module.exports = (req, res, next) => {
  console.log(req.body);
  next();
};
router.post('',
  testBoby,
  celebrate(validators.create),
  jwtVerify,
  extractFile,
  controllers.create
);
```

I can see 

**{}**

an empty object

**Comment by arb** [comment]
Put a log statement like this

```
router.post('',
  (req, res, next) => { console.log(req.body); next(); }
  celebrate(validators.create),
  jwtVerify,
  extractFile,
  controllers.create
);
```

If it's an empty object, then you have an issue before this route. You've posted a lot of disjointed code so it's hard to see exactly what your server is doing.

**Comment by whisher** [comment]
this is my testBody like your example :)
```javascript
module.exports = (req, res, next) => {
  console.log(req.body);
  next();
};
```
and it logs an empty object

**Comment by whisher** [comment]
I've just tried  
https://github.com/arb/celebrate/issues/79#issuecomment-412279514  
(at the end)
but it doesn't work :(

**Comment by arb** [comment]
Like I said, keep moving the logging statement around until `req.body` is not empty. Looking at the documentation to `multer` this isn't a problem with celebrate and you're just having issues with putting it in the right position. celebrate only validations against `req.body`, if you have it in a position where `req.body` is an empty object, the validation is going to fail. 

Also looking (again) at the `multer` docs, I see this note:

> Note that req.body might not have been fully populated yet. It depends on the order that the client transmits fields and files to the server.

So it may be impossible to do this the way you have it written.

Additionally, you can check through the `multer` issues related to [`req.body`](https://github.com/expressjs/multer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+req.body), it seems you aren't the only person with issues of `req.body` being empty.

**Comment by arb** [comment]
Were you ever able to figure out this issue?

**Comment by whisher** [comment]
No, I wasn't :(

**Comment by leoyoshii** [comment]
> Ok so if `req.body` is an empty object, then `multer` isn't parsing the multipart form before `req` is passing through the `celebrate` middleware. You probably have to move it down past `extractFile`. What I would do is keep moving the logging statement down until `req.body` has some values, and then put the validation middleware at that spot.

This is worked for me, Thanks  👍.

`postRouter.post(
  '/',
  upload.array('photos'),
  celebrate({
    [Segments.BODY]: {
      text: Joi.string().required(),
      title: Joi.string().required(),
    },
  }),
  postController.create,
);`
